# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='session_key',
            field=models.CharField(default='none', max_length=120),
            preserve_default=False,
        ),
    ]
