# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
