# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
    ]
