# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_price_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
